version: '3.3'

services:
  app:
    image: 'docker-ilerna-be:latest'
    build:
      context: .                          #docker file path (. means root directory)
      dockerfile: Dockerfile              #docker file name
    container_name: app-ilerna-be
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/flashes
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=Rperezbea2
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - "8080:8080"
  db:
    image: mysql/mysql-server
    container_name: mysql-db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Rperezbea2
      MYSQL_DATABASE: flashes
      MYSQL_ROOT_HOST: 172.18.0.1
    expose:
      - '3306'
    ports:
      - "3306:3306"
