version: '3.3'

services:
  app:
    image: 'docker-ilerna-be:latest'
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app-ilerna-be
    depends_on:
      - db
    environment:
      spring.datasource.url: jdbc:mysql://db:3306/flashes
      spring.datasource.username: "root"
      spring.datasource.password: "Rperezbea2"
      spring.jpa.properties.hibernate.dialect: "org.hibernate.dialect.MySQL8Dialect"
    ports:
      - 8080:8080
    expose:
      - 8080
  db:
    image: mysql/mysql-server
    container_name: db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Rperezbea2
      MYSQL_DATABASE: flashes
      MYSQL_ROOT_HOST: '%'
    expose:
      - 3306
    ports:
      - "3306:3306"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-mysql
    links:
      - db
    restart: always
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    ports:
      - "8083:80"


